"use client";

import { 
  Document, 
  Page, 
  Text, 
  View, 
  StyleSheet 
} from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    padding: 60,
    backgroundColor: "#fff",
  },
  receiptContainer: {
    border: 2,
    borderColor: "#e2e8f0",
    padding: 40,
    borderRadius: 12,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 40,
  },
  schoolName: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#3b82f6",
  },
  receiptNo: {
    fontSize: 10,
    color: "#64748b",
  },
  watermark: {
    position: "absolute",
    top: "40%",
    left: "20%",
    fontSize: 80,
    color: "#f1f5f9",
    opacity: 0.5,
    transform: "rotate(-45deg)",
    zIndex: -1,
  },
  title: {
    fontSize: 28,
    fontWeight: "black",
    color: "#1e293b",
    marginBottom: 30,
    textAlign: "center",
  },
  section: {
    marginBottom: 20,
  },
  label: {
    fontSize: 10,
    color: "#94a3b8",
    textTransform: "uppercase",
    marginBottom: 4,
  },
  value: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#334155",
  },
  amountBox: {
    marginTop: 40,
    padding: 20,
    backgroundColor: "#f8fafc",
    borderRadius: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  amountValue: {
    fontSize: 24,
    fontWeight: "black",
    color: "#3b82f6",
  },
  footerText: {
    marginTop: 100,
    fontSize: 9,
    color: "#94a3b8",
    textAlign: "center",
    lineHeight: 1.5,
  }
});

interface PaymentReceiptPDFProps {
  receipt: any;
}

export const PaymentReceiptPDF = ({ receipt }: PaymentReceiptPDFProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.receiptContainer}>
        <View style={styles.watermark}>
           <Text>PAID</Text>
        </View>

        <View style={styles.header}>
           <Text style={styles.schoolName}>KLAXTRIX INSTITUTION</Text>
           <Text style={styles.receiptNo}>Receipt No: {receipt.reference}</Text>
        </View>

        <Text style={styles.title}>Official Fee Receipt</Text>

        <View style={styles.section}>
           <Text style={styles.label}>Payer Name</Text>
           <Text style={styles.value}>{receipt.parentName}</Text>
        </View>

        <View style={styles.section}>
           <Text style={styles.label}>Student Beneficiary</Text>
           <Text style={styles.value}>{receipt.studentName} ({receipt.admissionNo})</Text>
        </View>

        <View style={styles.section}>
           <Text style={styles.label}>Purpose of Payment</Text>
           <Text style={styles.value}>{receipt.description}</Text>
        </View>

        <View style={styles.section}>
           <Text style={styles.label}>Payment Date</Text>
           <Text style={styles.value}>{new Date(receipt.date).toLocaleDateString()} at {new Date(receipt.date).toLocaleTimeString()}</Text>
        </View>

        <View style={styles.amountBox}>
           <Text style={styles.label}>Amount Cleared</Text>
           <Text style={styles.amountValue}>₦{receipt.amount.toLocaleString()}</Text>
        </View>

        <Text style={styles.footerText}>
          This is an electronically transmitted confirmation generated by the Paystack Financial Gateway and Klaxtrix Ledger. Keep this for your official records. Thank you for your commitment to excellence.
        </Text>
      </View>
    </Page>
  </Document>
);
